name: symbol_sdk
description: Symbol and Nem sdk for Dart and Flutter
version: 1.0.1
author: toshi
license: MIT
repository: https://github.com/0x070696E65/symbol_dart_sdk.git

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  tuple: ^2.0.0
  ed25519_edwards: ^0.3.1
  base32: ^2.1.3
  hash: ^1.0.4
  web3dart: ^2.7.2
  bip39_mnemonic: ^3.0.6
  http: ^1.2.0
  cryptography: ^2.7.0
  pinenacl: ^0.5.1
  pointycastle: ^3.2.0
  crypto: ^3.0.1
  convert: ^3.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.25.2
