name: symbol_dart_sdk
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  tuple: ^2.0.0
  ed25519_edwards: ^0.3.1
  base32: ^2.1.3
  hash: ^1.0.4
  web3dart: ^2.7.2
  bip39_mnemonic: ^3.0.6
  http: ^1.2.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.25.2
